baseurl: /wiki
exclude:
  - .github/
github:
  source:
    branch: master
# List of paths to ignore for things like subpage/menu listings
paths_to_ignore:
  - 404.md
  - assets/css/style.scss
  - index.md
  - robots.txt
  - sitemap.xml
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme:
title: My wiki
